### ISSUE TITLE
`GetItem` and `SetItem` missing

### ISSUE THREAD

**Issue by DarwinNE** [autc04/multiversal#2]
I noticed `GetItem` and `SetItem` are currently missing.
If I am not wrong, `GetItem` should behave identically to `GetMenuItemText` and `SetItem` is the same of `SetMenuItemText`.

**Comment by autc04** [comment]
Yes, `GetItem` and `SetItem` are indeed just aliases for `GetMenuItemText` and `SetMenuItemText`.
On 68K, they are mapped to the same trap number, and on PPC, the old name (`GetItem`) should just be a `#define` for the new name.
There are probably many more instances of missing aliases.

Apple's Universal Headers stopped defining the old names by default at some point - you had to add some global `#define` to get them back. A similar mechanism should probably be added here.

**Comment by DarwinNE** [comment]
Thank you!

I think a global `#define` would indeed be an useful mechanism for activating the older aliases.

**Comment by autc04** [comment]
`GetItem` and `SetItem` have now been added (commit d7aac1e58d165c30fd3a0796e7b4745e78d34643).

To use them, you need to `#define OLDROUTINENAMES` before including any of the headers, just as you would need for Apple's interfaces.

So far I've only added the old names for a handful of menu manager functions; there are many more spread over all the various parts of the API that will still be missing.
